### ISSUE TITLE
Unknown error 123

### ISSUE THREAD

**Issue by Crigges** [peq/jMpq#1]
de.peeeq.jmpq.JmpqError: Error in extractFile :  unknown error: 123
    at de.peeeq.jmpq.JmpqEditor.handleResult(JmpqEditor.java:36)
    at de.peeeq.jmpq.JmpqEditor.extractFile(JmpqEditor.java:60)
    at ImportFile.extractImportedFiles(ImportFile.java:53)
    at ImportFile.main(ImportFile.java:69)

What means the error 123?

**Comment by peq** [comment]
I think you have to check the Windows System Error Codes: http://msdn.microsoft.com/en-us/library/windows/desktop/ms681382%28v=vs.85%29.aspx

But I am not sure, since this number is coming from the StormLib.

**Comment by peq** [comment]
(12:33:57) Crigges: ich hab sowas:
(12:34:05) Crigges: C:\Users\Crigges\Desktop\imports\ButtonC.mdx
(12:34:17) Crigges: merke mhh ist falsch da muss nen war3map imported vor
(12:34:28) Crigges: also mache ich war3mapImported\C:\Users\Crigges\Desktop\imports\ButtonC.mdx
